name: peft-thesis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers>=4.44.0
      - datasets>=2.20.0
      - evaluate>=0.4.0
      - accelerate>=0.33.0
      - peft>=0.13.0
      - matplotlib
      - pandas
      - scikit-learn
